# Script, generated by ChatGPT.
# It hadn't been checked, so run at your own risk

# uv run python3 -m scripts.seed_database --clear
# from root folder of project

import argparse
import random
import re
from datetime import datetime, timedelta

import pandas as pd
from faker import Faker
from huggingface_hub import hf_hub_download
from sqlalchemy.exc import SQLAlchemyError

from app import create_app
from app.extensions import db
from app.models.product import Product
from app.models.inspector import Inspector
from app.models.inspection import Inspection
from app.models.defect import Defect
from app.models.enums import (
    InspectionResultEnum,
    DefectSeverityEnum,
    DefectStatusEnum,
)


DATASET_REPO = "xpertsystems/mfg010-sample"
DATASET_FILE = "mfg010_defects.csv"

fake = Faker()
Faker.seed(42)
random.seed(42)


def clean_value(value):
    if value is None:
        return None

    if pd.isna(value):
        return None

    value = str(value).strip()

    if value == "" or value.lower() in ["nan", "none", "null"]:
        return None

    return value


def get_first_value(row, possible_columns, default=None):
    for column in possible_columns:
        if column in row:
            value = clean_value(row[column])

            if value is not None:
                return value

    return default


def cut(value, max_length):
    if value is None:
        return None

    return str(value)[:max_length]


def safe_code(value):
    value = str(value).upper()
    value = re.sub(r"[^A-Z0-9_-]", "-", value)
    value = re.sub(r"-+", "-", value)
    return value.strip("-")


def parse_inspection_datetime(row):
    inspection_date = get_first_value(
        row,
        ["inspection_date", "detected_date", "date"],
    )

    inspection_time = get_first_value(
        row,
        ["inspection_time", "detected_time", "time"],
    )

    if inspection_date and inspection_time:
        raw_value = f"{inspection_date} {inspection_time}"
    elif inspection_date:
        raw_value = inspection_date
    else:
        return fake.date_time_between(start_date="-90d", end_date="now")

    parsed = pd.to_datetime(raw_value, errors="coerce")

    if pd.isna(parsed):
        return fake.date_time_between(start_date="-90d", end_date="now")

    return parsed.to_pydatetime()


def map_inspection_result(row):
    result = get_first_value(
        row,
        ["inspection_result", "result", "image_label"],
        default="FAIL",
    )

    result = result.upper()

    if "PASS" in result or "OK" in result:
        return InspectionResultEnum.PASS

    if "WARNING" in result or "BORDERLINE" in result:
        return InspectionResultEnum.WARNING

    return InspectionResultEnum.FAIL


def map_defect_severity(row):
    severity_class = get_first_value(
        row,
        ["severity_class", "rpn_category", "aql_classification"],
    )

    severity_rating = get_first_value(
        row,
        ["severity_rating"],
    )

    if severity_class:
        value = severity_class.upper()

        if "CRITICAL" in value or "CATASTROPHIC" in value:
            return DefectSeverityEnum.CRITICAL

        if "HIGH" in value or "MAJOR" in value or "SEVERE" in value:
            return DefectSeverityEnum.HIGH

        if "MEDIUM" in value or "MODERATE" in value:
            return DefectSeverityEnum.MEDIUM

        return DefectSeverityEnum.LOW

    if severity_rating:
        try:
            rating = int(float(severity_rating))

            if rating >= 9:
                return DefectSeverityEnum.CRITICAL

            if rating >= 7:
                return DefectSeverityEnum.HIGH

            if rating >= 4:
                return DefectSeverityEnum.MEDIUM

            return DefectSeverityEnum.LOW

        except ValueError:
            return DefectSeverityEnum.MEDIUM

    return DefectSeverityEnum.MEDIUM


def map_defect_status(row):
    days_to_close = get_first_value(
        row,
        ["days_to_close", "capa_days_to_close"],
    )

    corrective_action = get_first_value(
        row,
        ["corrective_action_description", "corrective_action"],
    )

    containment_action = get_first_value(
        row,
        ["containment_action"],
    )

    if days_to_close:
        return DefectStatusEnum.CLOSED

    if corrective_action:
        return DefectStatusEnum.RESOLVED

    if containment_action:
        return DefectStatusEnum.IN_PROGRESS

    return DefectStatusEnum.OPEN


def get_resolved_at(row, detected_at, status):
    if status not in [DefectStatusEnum.RESOLVED, DefectStatusEnum.CLOSED]:
        return None

    days_to_close = get_first_value(
        row,
        ["days_to_close", "capa_days_to_close"],
    )

    if days_to_close:
        try:
            return detected_at + timedelta(days=int(float(days_to_close)))
        except ValueError:
            pass

    return detected_at + timedelta(days=random.randint(1, 10))


def download_dataset():
    path = hf_hub_download(
        repo_id=DATASET_REPO,
        filename=DATASET_FILE,
        repo_type="dataset",
    )

    return pd.read_csv(path)


def clear_database():
    Defect.query.delete()
    Inspection.query.delete()
    Product.query.delete()
    Inspector.query.delete()

    db.session.commit()


def get_or_create_product(row, index, product_cache):
    product_code = get_first_value(
        row,
        ["part_number", "part_id", "product_code"],
        default=f"PRODUCT-{index}",
    )

    product_code = cut(safe_code(product_code), 50)

    if product_code in product_cache:
        return product_cache[product_code]

    product = Product.query.filter_by(product_code=product_code).first()

    if product:
        product_cache[product_code] = product
        return product

    name = get_first_value(
        row,
        ["part_name", "product_name", "name"],
        default=f"Product {product_code}",
    )

    product_family = get_first_value(
        row,
        ["product_family", "industry_sector"],
        default="General Manufacturing",
    )

    revision = get_first_value(
        row,
        ["revision", "engineering_change"],
        default=f"REV-{random.choice(['A', 'B', 'C', 'D'])}",
    )

    product = Product(
        product_code=product_code,
        name=cut(name, 100),
        product_family=cut(product_family, 100),
        revision=cut(revision, 30),
        is_active=True,
    )

    db.session.add(product)
    db.session.flush()

    product_cache[product_code] = product

    return product


def get_or_create_inspector(row, index, inspector_cache):
    employee_number = get_first_value(
        row,
        ["inspector_id", "operator_id"],
        default=f"INS-{index % 50:03d}",
    )

    employee_number = cut(safe_code(employee_number), 50)

    if employee_number in inspector_cache:
        return inspector_cache[employee_number]

    inspector = Inspector.query.filter_by(
        employee_number=employee_number
    ).first()

    if inspector:
        inspector_cache[employee_number] = inspector
        return inspector

    first_name = fake.first_name()
    last_name = fake.last_name()

    email_key = employee_number.lower().replace("_", ".").replace("-", ".")
    email = f"{email_key}@example.com"

    department = get_first_value(
        row,
        ["station_id", "work_center"],
        default="Quality",
    )

    inspector = Inspector(
        employee_number=employee_number,
        first_name=cut(first_name, 100),
        last_name=cut(last_name, 100),
        email=cut(email, 150),
        department=cut(department, 100),
        role="Quality Inspector",
        is_active=True,
    )

    db.session.add(inspector)
    db.session.flush()

    inspector_cache[employee_number] = inspector

    return inspector


def create_inspection(row, index, product, inspector):
    inspection_date = parse_inspection_datetime(row)

    batch_number = get_first_value(
        row,
        ["batch_lot_number", "batch_number", "lot_number"],
        default=f"BATCH-{random.randint(1000, 9999)}",
    )

    serial_number = get_first_value(
        row,
        ["serial_number"],
        default=f"SN-{index:06d}",
    )

    result = map_inspection_result(row)

    inspection = Inspection(
        batch_number=cut(batch_number, 50),
        serial_number=cut(serial_number, 100),
        inspection_date=inspection_date,
        result=result,
        notes="Seeded from Hugging Face xpertsystems/mfg010-sample.",
        product_id=product.id,
        inspector_id=inspector.id,
    )

    db.session.add(inspection)
    db.session.flush()

    return inspection


def create_defect(row, index, product, inspection):
    detected_at = inspection.inspection_date
    severity = map_defect_severity(row)
    status = map_defect_status(row)

    defect_code = get_first_value(
        row,
        ["defect_code"],
        default=f"D-{index:05d}",
    )

    defect_type = get_first_value(
        row,
        ["defect_type", "defect_category", "defect_subcategory"],
        default="Unknown Defect",
    )

    description = get_first_value(
        row,
        ["defect_description", "description"],
        default=f"Generated defect record for {defect_type}.",
    )

    root_cause = get_first_value(
        row,
        [
            "root_cause_primary",
            "root_cause_category",
            "primary_root_cause",
            "root_cause",
        ],
    )

    corrective_action = get_first_value(
        row,
        [
            "corrective_action_description",
            "corrective_action",
            "containment_action",
        ],
    )

    resolved_at = get_resolved_at(row, detected_at, status)

    defect = Defect(
        defect_code=cut(defect_code, 50),
        defect_type=cut(defect_type, 100),
        severity=severity,
        status=status,
        description=description,
        detected_at=detected_at,
        resolved_at=resolved_at,
        root_cause=root_cause,
        corrective_action=corrective_action,
        product_id=product.id,
        inspection_id=inspection.id,
    )

    db.session.add(defect)
    db.session.flush()

    return defect


def create_generated_pass_inspections(amount, products, inspectors):
    inspections = []

    for index in range(1, amount + 1):
        product = random.choice(products)
        inspector = random.choice(inspectors)

        inspection = Inspection(
            batch_number=f"PASS-BATCH-{random.randint(1000, 9999)}",
            serial_number=f"PASS-SN-{index:06d}",
            inspection_date=fake.date_time_between(
                start_date="-90d",
                end_date="now",
            ),
            result=InspectionResultEnum.PASS,
            notes="Generated PASS inspection to balance defect-event dataset.",
            product_id=product.id,
            inspector_id=inspector.id,
        )

        db.session.add(inspection)
        inspections.append(inspection)

    db.session.flush()

    return inspections


def seed_from_huggingface(clear=False, limit=1000, pass_inspections=100):
    if clear:
        clear_database()

    df = download_dataset()

    if limit and limit > 0:
        df = df.head(limit)

    product_cache = {}
    inspector_cache = {}

    created_inspections = []
    created_defects = []

    for index, row in df.iterrows():
        row = row.to_dict()

        product = get_or_create_product(
            row=row,
            index=index,
            product_cache=product_cache,
        )

        inspector = get_or_create_inspector(
            row=row,
            index=index,
            inspector_cache=inspector_cache,
        )

        inspection = create_inspection(
            row=row,
            index=index,
            product=product,
            inspector=inspector,
        )

        defect = create_defect(
            row=row,
            index=index,
            product=product,
            inspection=inspection,
        )

        created_inspections.append(inspection)
        created_defects.append(defect)

    products = list(product_cache.values())
    inspectors = list(inspector_cache.values())

    created_pass_inspections = create_generated_pass_inspections(
        amount=pass_inspections,
        products=products,
        inspectors=inspectors,
    )

    db.session.commit()

    return {
        "dataset": DATASET_REPO,
        "dataset_file": DATASET_FILE,
        "products": len(products),
        "inspectors": len(inspectors),
        "defect_inspections": len(created_inspections),
        "pass_inspections": len(created_pass_inspections),
        "defects": len(created_defects),
    }


def main():
    parser = argparse.ArgumentParser(
        description="Seed QM database using Hugging Face manufacturing defect dataset."
    )

    parser.add_argument(
        "--clear",
        action="store_true",
        help="Delete existing data before inserting seed data.",
    )

    parser.add_argument(
        "--limit",
        type=int,
        default=1000,
        help="Number of Hugging Face dataset rows to import. Use 0 for all rows.",
    )

    parser.add_argument(
        "--pass-inspections",
        type=int,
        default=100,
        help="Number of generated PASS inspections to add.",
    )

    args = parser.parse_args()

    app = create_app()

    with app.app_context():
        try:
            result = seed_from_huggingface(
                clear=args.clear,
                limit=args.limit,
                pass_inspections=args.pass_inspections,
            )

            print("Database seeded successfully.")
            print(f"Dataset: {result['dataset']}")
            print(f"Dataset file: {result['dataset_file']}")
            print(f"Products: {result['products']}")
            print(f"Inspectors: {result['inspectors']}")
            print(f"Defect inspections: {result['defect_inspections']}")
            print(f"Generated PASS inspections: {result['pass_inspections']}")
            print(f"Defects: {result['defects']}")

        except SQLAlchemyError as error:
            db.session.rollback()
            print("Database seeding failed.")
            print(error)

        except Exception as error:
            db.session.rollback()
            print("Unexpected seeding error.")
            print(error)


if __name__ == "__main__":
    main()